name: Build and publish

on:
  workflow_dispatch:
    inputs:
      release:
        description: 发布 Release
        required: true
        type: boolean
  push:
    branches:
      - "main"
      - "release"
    paths:
      - ".github/**"
      - ".vitepress/**"
      - "src/**"
      - "theme/**"
      - "book.toml"
      - "package-lock.json"
      - "package.json"

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: current
          cache: npm

      - name: Install node packages
        run: npm ci

      - name: Install mdBook
        uses: baptiste0928/cargo-install@v2
        with:
          crate: mdbook
          git: https://github.com/rust-lang/mdBook

      - name: Install mdbook-epub
        uses: baptiste0928/cargo-install@v2
        with:
          crate: mdbook-epub
          git: https://github.com/Michael-F-Bryan/mdbook-epub

      - name: Install mdbook-typst-pdf
        uses: baptiste0928/cargo-install@v2
        with:
          crate: mdbook-typst-pdf
          git: https://github.com/KaiserY/mdbook-typst-pdf

      - name: Install fonts
        run: |
          mkdir -p ~/.local/share/fonts/
          curl -sL -o Noto_Sans.zip https://fonts.google.com/download?family=Noto%20Sans
          unzip Noto_Sans.zip -d ~/.local/share/fonts/Noto_Sans
          curl -sL -o Noto_Sans_SC.zip https://fonts.google.com/download?family=Noto%20Sans%20SC
          unzip Noto_Sans_SC.zip -d ~/.local/share/fonts/Noto_Sans_SC
          curl -sL -o Noto_Sans_Mono.zip https://fonts.google.com/download?family=Noto%20Sans%20Mono
          unzip Noto_Sans_Mono.zip -d ~/.local/share/fonts/Noto_Sans_Mono
          rm -fv ~/.local/share/fonts/Noto_Sans_Mono/NotoSansMono-VariableFont_wdth,wght.ttf
          curl -sL -o Noto_Sans_KR.zip https://fonts.google.com/download?family=Noto%20Sans%20KR
          unzip Noto_Sans_KR.zip -d ~/.local/share/fonts/Noto_Sans_KR
          curl -sL -o Noto_Sans_Thai.zip https://fonts.google.com/download?family=Noto%20Sans%20Thai
          unzip Noto_Sans_Thai.zip -d ~/.local/share/fonts/Noto_Sans_Thai
          rm -fv ~/.local/share/fonts/Noto_Sans_Thai/NotoSansThai-VariableFont_wdth,wght.ttf
          curl -sL -o Noto_Sans_Arabic.zip https://fonts.google.com/download?family=Noto%20Sans%20Arabic
          unzip Noto_Sans_Arabic.zip -d ~/.local/share/fonts/Noto_Sans_Arabic
          curl -sL -o Noto_Sans_Hebrew.zip https://fonts.google.com/download?family=Noto%20Sans%20Hebrew
          unzip Noto_Sans_Hebrew.zip -d ~/.local/share/fonts/Noto_Sans_Hebrew
          curl -sL -o Noto_Sans_Devanagari.zip https://fonts.google.com/download?family=Noto%20Sans%20Devanagari
          unzip Noto_Sans_Devanagari.zip -d ~/.local/share/fonts/Noto_Sans_Devanagari
          rm -fv ~/.local/share/fonts/Noto_Sans_Devanagari/NotoSansDevanagari-VariableFont_wdth,wght.ttf
          curl -sL -o Noto_Emoji.zip https://fonts.google.com/download?family=Noto%20Emoji
          unzip Noto_Emoji.zip -d ~/.local/share/fonts/Noto_Emoji
          curl -sL -o times_sans_serif.zip https://dl.dafont.com/dl/?f=times_sans_serif
          unzip times_sans_serif.zip -d ~/.local/share/fonts/times_sans_serif
          fc-cache -rv

      - name: Install Calibre
        run: |
          sudo apt install -y libegl1 libopengl0 libxcb-cursor0
          sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

      - name: Build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          sed -e "s/BUILD_TIME/$(TZ=Asia/Shanghai date -Isecond)/" -e "s/COMMIT_SHA/${{ github.sha }}/" -i src/about.md
          npm run build
          mv book/epub/药娘的天空.epub book/epub/transky-${{ github.sha }}.epub
          mv book/mobi/药娘的天空.mobi book/mobi/transky-${{ github.sha }}.mobi
          mv book/typst-pdf/药娘的天空.pdf book/typst-pdf/transky-${{ github.sha }}.pdf

      - name: Upload EPUB
        uses: actions/upload-artifact@v4
        with:
          name: epub
          path: book/epub/transky-*.epub

      - name: Upload MOBI
        uses: actions/upload-artifact@v4
        with:
          name: mobi
          path: book/mobi/transky-*.mobi

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: book/typst-pdf/transky-*.pdf

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_PAGES_ACCOUNT }}
          projectName: proskynova-github-io
          directory: .vitepress/dist/
          wranglerVersion: 3

      - name: Release eBook
        if: ${{ (github.event_name == 'workflow_dispatch' && inputs.release) || ! (github.event_name == 'push' && contains(github.event.head_commit.message, '[skip release]')) }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: npx semantic-release
